# Generated by Django 4.1.7 on 2023-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_in_min', models.IntegerField(blank=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
